AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: First working Lambda Pipeline

Resources:

    PhantomLambda:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: nodejs6.10
            Description: Extract an XPath from web pages and convert to JSON
            CodeUri: .
            MemorySize: 1024
            Timeout: 300
Outputs:
  LambdaFunction:
    Description: The bucket that holds all the builds
    Value: !Ref PhantomLambda